name             'base-server'
maintainer       'John'
maintainer_email 'virginian@blueyonder.co.uk'
license          'All rights reserved'
description      'Installs/Configures base-server'
long_description 'Installs/Configures base-server'
version          '0.1.0'

depends 'yum'
depends 'yum-epel'
depends 'auto-update'
